##################################################################################################################################        
# Oracle Fusion Middleware 12.2 Infrastructure installation playbook 
# Developed by Fernando Hackbart (fhackbart@gmail.com)
# Lisbon 2017-12-28

- name: Oracle Fusion Middleware 12.2 OHS installation 
  hosts: "{{ targetHosts }}"
  user: "{{ targetUser }}"
  become: true
  become_user: oracle
  become_method: sudo
  roles: 
    - ofm-ohs-122
