##################################################################################################################################        
# Oracle Fusion Middleware 12.2 Infrastructure installation playbook 
# Developed by Fernando Hackbart (fhackbart@gmail.com)
# Lisbon 2017-12-28
---
- name: Oracle Fusion Middleware 12.2 domain unpack
  hosts: "{{ unpackHosts }}"
  user: "{{ targetUser }}"
  become: true
  become_user: oracle
  become_method: sudo
  roles: 
    - ofm-infra-122
    - ofm-domain-unpack
