##################################################################################################################################        
# Oracle Fusion Middleware 12.2 Infrastructure installation playbook 
# Developed by Fernando Hackbart (fhackbart@gmail.com)
# Lisbon 2017-12-28
---  
# Create stagedir for domain
- name: Check if OFM domain {{ ofmDomainName }} exists at {{ ofmDomainHome }}
  stat: 
    path: "{{ ofmDomainHome }}"
  register: ofmDomainHome_configured   
  
- name: Packing the domain {{ ofmDomainName }}
  block:
  
  - name: Create stage folder {{ ofmDomainStageDir }}
    file:
      path: "{{ ofmDomainStageDir }}"
      state: directory
      mode: "{{ mode }}"
      
   
  - name: Copying the packed domain from the Ansible server to {{ ofmDomainStageDir }}/Pack-{{ ofmDomainName }}.jar
    copy: 
      src: "{{ ofmAdminserverMachine }}/{{ ofmDomainStageDir }}/Pack-{{ ofmDomainName }}.jar"
      dest: "{{ ofmDomainStageDir }}/Pack-{{ ofmDomainName }}.jar"


  - name: Unpacking domain {{ ofmDomainName }} to {{ ofmDomainHome }} from {{ ofmDomainStageDir }}/Pack-{{ ofmDomainName }}.jar
    shell: "{{ oracleHome }}/oracle_common/common/bin/unpack.sh -initialize=false -template={{ ofmDomainStageDir }}/Pack-{{ ofmDomainName }}.jar -domain={{ ofmDomainHome }} -app_dir={{ ofmApplicationHome }} -nodemanager_type=PerDomainNodeManager -log={{ ofmDomainLogsHome }}/Unpack-{{ ofmDomainName }}.log -log_priority=info"
    args:
      chdir: "{{oracleHome }}/oracle_common/bin"
    environment:
      JAVA_HOME: "{{ javaHome }}"
      JAVA_OPTIONS: "{{ ofmUrandomArgs }}"
      ORACLE_HOME: "{{ oracleHome }}"
      TEMP: "{{ tempDir }}"
         
  - name: Create start nodemanager bash script {{ ofmDomainStageDir }}/OFM-12.2-startNodeManager.sh
    template: 
      src: "OFM-12.2-startNodeManager.sh"
      dest: "{{ ofmDomainStageDir }}/OFM-12.2-startNodeManager.sh"    
      mode: "{{ secureMode }}"
      
  - name: Create wait nodemanager Jython script {{ ofmDomainStageDir }}/OFM-waitNodeManager.py
    template: 
      src: "OFM-waitNodeManager.py"
      dest: "{{ ofmDomainStageDir }}/OFM-waitNodeManager.py"    
      mode: "{{ secureMode }}"

  - name: Start nodemanager with {{ ofmDomainStageDir }}/OFM-12.2-startNodeManager.sh
    command: "{{ ofmDomainStageDir }}/OFM-12.2-startNodeManager.sh"
    args:
      chdir: "{{ ofmDomainStageDir }}"
    environment:
      JAVA_HOME: "{{ javaHome }}"
      JAVA_OPTIONS: "{{ ofmUrandomArgs }}"
      NODEMGR_HOME: "{{ ofmDomainHome }}/nodemanager"      
      TEMP: "{{ tempDir }}"
         
  - name: Wait the startup of nodemanager {{ ofmDomainName }} at {{ ofmDomainHome }}
    command: "{{oracleHome }}/oracle_common/common/bin/wlst.sh  {{ ofmDomainStageDir }}/OFM-waitNodeManager.py"
    args:
      chdir: "{{oracleHome }}/oracle_common/common/bin"
    environment:
      JAVA_HOME: "{{ javaHome }}"
      JAVA_OPTIONS: "{{ ofmUrandomArgs }}"
      TEMP: "{{ tempDir }}"
    
  when: >
    ofmDomainHome_configured.stat.exists == False