##################################################################################################################################        
# Oracle Fusion Middleware 12.2 Infrastructure installation playbook 
# Developed by Fernando Hackbart (fhackbart@gmail.com)
# Lisbon 2017-12-28
---
ofmDomainName: "XPTO001"
ofmLogHome: "/u01/oracle/log"
ofmDomainLogsHome: "{{ ofmLogHome }}/domains/{{ ofmDomainName }}"
ofmConfigHome: "/u01/oracle/config"
ofmConfigRequiredSpace: 2095005696
ofmDomainBase: "{{ ofmConfigHome }}/domains"
ofmDomainHome: "{{ ofmDomainBase }}/{{ ofmDomainName }}"
ofmApplicationBase: "{{ ofmConfigHome }}/applications"
ofmApplicationHome: "{{ ofmApplicationBase }}/{{ ofmDomainName }}"
ofmTransactionsHome: "/u01/oracle/transaction"
ofmTransBase: "{{ ofmTransactionsHome }}/domains"
ofmTransHome: "{{ ofmTransBase }}/{{ ofmDomainName }}"
ofmDomainStageDir: "{{ stageDir }}/{{ ofmDomainName }}"

ofmRestrictedJRF: "TRUE"
ofmRCUOperation: "createRepository"
ofmExtRCUOperation: "appendRepository"
ofmJdbcURL: "(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=server20.xpto.com)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=daggpunkt.xpto.com)))"
ofmJdbcURLrcu: "server20.xpto.com:1521/daggpunkt.xpto.com"
ofmJdbctest: " DUAL "
ofmJdbcsysUsername: "sys" 
ofmJDBCsysrole: "sysdba"
ofmJdbcsysPassword: "Welcome1" 
ofmJdbcRCUSchemaPrefix: "{{ ofmDomainName }}" 
ofmJdbcRCUPassword: "Welcome1" 
ofmRCUComponents: "STB,IAU_APPEND,OPSS,IAU,MDS,WLS,IAU_VIEWER"
ofmNodemgrPort: "12000"
ofmNodemgrUsername: "{{ ofmDomainName }}NodeManager" 
ofmNodemgrPassword: "Welcome1" 
ofmCOHClustername: "defaultCoherenceCluster" 
ofmCOHUnicastport: "12010" 
ofmAdminserverName: "AdminServer" 
ofmAdminserverPort: "12001" 
ofmAdminservermsArsg: " -Xms700m -Xmx700m " 
ofmUrandomArgs: " -Djava.security.egd=file:/dev/./urandom "
ofmAdminserverMachine: "server22.xpto.com"
ofmAdminPassword: "Welcome1" 
ofmTemplateDomainName: "base_domain"
ofmTemplateJDBCPrefix: "DEV"
