##################################################################################################################################        
# Oracle Fusion Middleware 12.2 Infrastructure installation playbook 
# Developed by Fernando Hackbart (fhackbart@gmail.com)
# Lisbon 2017-12-28
---  
- name: Checking serverEnvironment = {{ serverEnvironment }}
  fail:
    msg: "serverEnvironment = {{ serverEnvironment }} not valid!"
  when: > 
         ((not (serverEnvironment in highenvs)) and (not(serverEnvironment in lowenvs)))
         
- name: Check if OFM home {{ oraclePresenceFolder }} is already installed 
  stat: path={{ oraclePresenceFolder }}
  register: oracleHome_installed

- name: Installing Oracle Fusion Middleware Infrastructure
  block:
  - name: Check available disk space in {{ tempBaseVolume }}
    assert:
      that: 
        -  item.size_available > tempRequiredSpace
    with_items: 
      - "{{ ansible_mounts }}"
    when: >
      item.mount == tempBaseVolume
    register: tmp_free

  - name: Check available disk space in {{ oraBaseVolume }}
    assert:
      that: 
        -  item.size_available > ofmInstallRequiredSpace
    with_items: 
      - "{{ ansible_mounts }}"
    when: >
      item.mount == oraBaseVolume    
    register: install_free 

  - name: Create base folder {{ oraBaseDir }}
    ignore_errors: yes
    file:
      path: "{{ oraBaseDir }}"
      state: directory
      mode: "{{ mode }}"
    
  - name: Create stage folder "{{ stageDir }}"
    file:
      path: "{{ stageDir }}"
      state: directory
      mode: "{{ mode }}"

  - name: Create response file {{ stageDir }}/{{ ofmresponseFile }}
    template: 
      src: "{{ ofmresponseFile }}"
      dest: "{{ stageDir }}/{{ ofmresponseFile }}"

  - name: Pre clean {{ stageDir }}/{{ ofmInstallationFile }}
    file: 
      path: "{{ stageDir }}/{{ ofmInstallationFile }}" 
      state: absent
    
  - name: Download Oracle Fusion Middleware Infrastructure from {{ mediasURL }}/{{ ofmInstallationMedia }} to {{ stageDir }}/{{ ofmInstallationMedia }}
    get_url: 
      url: "{{ mediasURL }}/{{ ofmInstallationMedia }}"
      dest: "{{ stageDir }}/{{ ofmInstallationMedia }}"
    when: > 
      mediassource == 'webserver'

  - name: Unzip {{ stageDir }}/{{ ofmInstallationMedia }} to {{ stageDir }}
    unarchive: 
      dest: "{{ stageDir }}"
      src: "{{ stageDir }}/{{ ofmInstallationMedia }}"
      creates: "{{ stageDir }}/{{ ofmInstallationFile }}"
      copy: no
    
  - name: Removing installation media {{ stageDir }}/{{ ofmInstallationMedia }}
    file: 
      path: "{{ stageDir }}/{{ ofmInstallationMedia }}" 
      state: absent

  - name: Installing Oracle Fusion Middleware {{ ofmVersion }} on {{ oracleHome }}
    command: "{{ javaExecutable }} -jar {{ stageDir }}/{{ ofmInstallationFile }} -silent -responseFile {{ stageDir }}/{{ ofmresponseFile }}"
    environment:
      JAVA_HOME: "{{ javaHome }}"
    
  - name: Post clean {{ stageDir }}/{{ ofmInstallationFile }}
    file: 
      path: "{{ stageDir }}/{{ ofmInstallationFile }}" 
      state: absent
    
  - name: Post clean {{ stageDir }}/{{ ofmresponseFile }}
    file: 
      path: "{{ stageDir }}/{{ ofmresponseFile }}" 
      state: absent
      
  when: >
    oracleHome_installed.stat.exists == False   
    
